/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BrevoConfig
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T19:02:02.404+06:00")
public class BrevoConfig   {
  @SerializedName("experimentId")
  private Long experimentId = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("senderEmail")
  private String senderEmail = null;

  @SerializedName("senderName")
  private String senderName = null;

  @SerializedName("targetGroupId")
  private Long targetGroupId = null;

  public BrevoConfig experimentId(Long experimentId) {
    this.experimentId = experimentId;
    return this;
  }

   /**
   * Get experimentId
   * @return experimentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getExperimentId() {
    return experimentId;
  }

  public void setExperimentId(Long experimentId) {
    this.experimentId = experimentId;
  }

  public BrevoConfig id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public BrevoConfig senderEmail(String senderEmail) {
    this.senderEmail = senderEmail;
    return this;
  }

   /**
   * Get senderEmail
   * @return senderEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSenderEmail() {
    return senderEmail;
  }

  public void setSenderEmail(String senderEmail) {
    this.senderEmail = senderEmail;
  }

  public BrevoConfig senderName(String senderName) {
    this.senderName = senderName;
    return this;
  }

   /**
   * Get senderName
   * @return senderName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSenderName() {
    return senderName;
  }

  public void setSenderName(String senderName) {
    this.senderName = senderName;
  }

  public BrevoConfig targetGroupId(Long targetGroupId) {
    this.targetGroupId = targetGroupId;
    return this;
  }

   /**
   * Get targetGroupId
   * @return targetGroupId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTargetGroupId() {
    return targetGroupId;
  }

  public void setTargetGroupId(Long targetGroupId) {
    this.targetGroupId = targetGroupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrevoConfig brevoConfig = (BrevoConfig) o;
    return Objects.equals(this.experimentId, brevoConfig.experimentId) &&
        Objects.equals(this.id, brevoConfig.id) &&
        Objects.equals(this.senderEmail, brevoConfig.senderEmail) &&
        Objects.equals(this.senderName, brevoConfig.senderName) &&
        Objects.equals(this.targetGroupId, brevoConfig.targetGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(experimentId, id, senderEmail, senderName, targetGroupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrevoConfig {\n");
    
    sb.append("    experimentId: ").append(toIndentedString(experimentId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    senderEmail: ").append(toIndentedString(senderEmail)).append("\n");
    sb.append("    senderName: ").append(toIndentedString(senderName)).append("\n");
    sb.append("    targetGroupId: ").append(toIndentedString(targetGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

