/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CampaignDto;
import io.swagger.client.model.Experiment;
import io.swagger.client.model.TargetGroupMessage;
import java.util.ArrayList;
import java.util.List;


/**
 * CampaignTargetGroupResponseDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class CampaignTargetGroupResponseDto   {
  @SerializedName("campaign")
  private CampaignDto campaign = null;

  @SerializedName("experiments")
  private List<Experiment> experiments = new ArrayList<Experiment>();

  @SerializedName("targetGroupMessages")
  private List<TargetGroupMessage> targetGroupMessages = new ArrayList<TargetGroupMessage>();

  public CampaignTargetGroupResponseDto campaign(CampaignDto campaign) {
    this.campaign = campaign;
    return this;
  }

   /**
   * Get campaign
   * @return campaign
  **/
  @ApiModelProperty(example = "null", value = "")
  public CampaignDto getCampaign() {
    return campaign;
  }

  public void setCampaign(CampaignDto campaign) {
    this.campaign = campaign;
  }

  public CampaignTargetGroupResponseDto experiments(List<Experiment> experiments) {
    this.experiments = experiments;
    return this;
  }

  public CampaignTargetGroupResponseDto addExperimentsItem(Experiment experimentsItem) {
    this.experiments.add(experimentsItem);
    return this;
  }

   /**
   * Get experiments
   * @return experiments
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Experiment> getExperiments() {
    return experiments;
  }

  public void setExperiments(List<Experiment> experiments) {
    this.experiments = experiments;
  }

  public CampaignTargetGroupResponseDto targetGroupMessages(List<TargetGroupMessage> targetGroupMessages) {
    this.targetGroupMessages = targetGroupMessages;
    return this;
  }

  public CampaignTargetGroupResponseDto addTargetGroupMessagesItem(TargetGroupMessage targetGroupMessagesItem) {
    this.targetGroupMessages.add(targetGroupMessagesItem);
    return this;
  }

   /**
   * Get targetGroupMessages
   * @return targetGroupMessages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TargetGroupMessage> getTargetGroupMessages() {
    return targetGroupMessages;
  }

  public void setTargetGroupMessages(List<TargetGroupMessage> targetGroupMessages) {
    this.targetGroupMessages = targetGroupMessages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignTargetGroupResponseDto campaignTargetGroupResponseDto = (CampaignTargetGroupResponseDto) o;
    return Objects.equals(this.campaign, campaignTargetGroupResponseDto.campaign) &&
        Objects.equals(this.experiments, campaignTargetGroupResponseDto.experiments) &&
        Objects.equals(this.targetGroupMessages, campaignTargetGroupResponseDto.targetGroupMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaign, experiments, targetGroupMessages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignTargetGroupResponseDto {\n");
    
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    experiments: ").append(toIndentedString(experiments)).append("\n");
    sb.append("    targetGroupMessages: ").append(toIndentedString(targetGroupMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

