/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CampaignDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class CampaignDto   {
  @SerializedName("channel")
  private String channel = null;

  @SerializedName("endDate_ui")
  private String endDateUi = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("startDate_ui")
  private String startDateUi = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("DRAFT")
    DRAFT("DRAFT"),
    
    @SerializedName("READY")
    READY("READY"),
    
    @SerializedName("STARTED")
    STARTED("STARTED"),
    
    @SerializedName("CANCELLED")
    CANCELLED("CANCELLED"),
    
    @SerializedName("COMPLETED")
    COMPLETED("COMPLETED"),
    
    @SerializedName("DELETED")
    DELETED("DELETED"),
    
    @SerializedName("FACEBOOK_TRANSFERRED")
    FACEBOOK_TRANSFERRED("FACEBOOK_TRANSFERRED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  /**
   * Gets or Sets strategy
   */
  public enum StrategyEnum {
    @SerializedName("SINGLE_ITERATION_RANDOM_MSG")
    SINGLE_ITERATION_RANDOM_MSG("SINGLE_ITERATION_RANDOM_MSG"),
    
    @SerializedName("GENETIC_ALGORITHM_V0")
    GENETIC_ALGORITHM_V0("GENETIC_ALGORITHM_V0"),
    
    @SerializedName("BEST_MESSAGES_ROUNDS_GA")
    BEST_MESSAGES_ROUNDS_GA("BEST_MESSAGES_ROUNDS_GA");

    private String value;

    StrategyEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("strategy")
  private StrategyEnum strategy = null;

  @SerializedName("teamOwnership")
  private String teamOwnership = null;

  @SerializedName("timezone_ui")
  private String timezoneUi = null;

  public CampaignDto channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public CampaignDto endDateUi(String endDateUi) {
    this.endDateUi = endDateUi;
    return this;
  }

   /**
   * Get endDateUi
   * @return endDateUi
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndDateUi() {
    return endDateUi;
  }

  public void setEndDateUi(String endDateUi) {
    this.endDateUi = endDateUi;
  }

  public CampaignDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CampaignDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CampaignDto startDateUi(String startDateUi) {
    this.startDateUi = startDateUi;
    return this;
  }

   /**
   * Get startDateUi
   * @return startDateUi
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDateUi() {
    return startDateUi;
  }

  public void setStartDateUi(String startDateUi) {
    this.startDateUi = startDateUi;
  }

  public CampaignDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CampaignDto strategy(StrategyEnum strategy) {
    this.strategy = strategy;
    return this;
  }

   /**
   * Get strategy
   * @return strategy
  **/
  @ApiModelProperty(example = "null", value = "")
  public StrategyEnum getStrategy() {
    return strategy;
  }

  public void setStrategy(StrategyEnum strategy) {
    this.strategy = strategy;
  }

  public CampaignDto teamOwnership(String teamOwnership) {
    this.teamOwnership = teamOwnership;
    return this;
  }

   /**
   * Get teamOwnership
   * @return teamOwnership
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTeamOwnership() {
    return teamOwnership;
  }

  public void setTeamOwnership(String teamOwnership) {
    this.teamOwnership = teamOwnership;
  }

  public CampaignDto timezoneUi(String timezoneUi) {
    this.timezoneUi = timezoneUi;
    return this;
  }

   /**
   * Get timezoneUi
   * @return timezoneUi
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimezoneUi() {
    return timezoneUi;
  }

  public void setTimezoneUi(String timezoneUi) {
    this.timezoneUi = timezoneUi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignDto campaignDto = (CampaignDto) o;
    return Objects.equals(this.channel, campaignDto.channel) &&
        Objects.equals(this.endDateUi, campaignDto.endDateUi) &&
        Objects.equals(this.id, campaignDto.id) &&
        Objects.equals(this.name, campaignDto.name) &&
        Objects.equals(this.startDateUi, campaignDto.startDateUi) &&
        Objects.equals(this.status, campaignDto.status) &&
        Objects.equals(this.strategy, campaignDto.strategy) &&
        Objects.equals(this.teamOwnership, campaignDto.teamOwnership) &&
        Objects.equals(this.timezoneUi, campaignDto.timezoneUi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, endDateUi, id, name, startDateUi, status, strategy, teamOwnership, timezoneUi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignDto {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    endDateUi: ").append(toIndentedString(endDateUi)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startDateUi: ").append(toIndentedString(startDateUi)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("    teamOwnership: ").append(toIndentedString(teamOwnership)).append("\n");
    sb.append("    timezoneUi: ").append(toIndentedString(timezoneUi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

