/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * CaseDistinctionConfigDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class CaseDistinctionConfigDto   {
  @SerializedName("capitalizeFullVariants")
  private Boolean capitalizeFullVariants = null;

  @SerializedName("customCapitalWords")
  private List<String> customCapitalWords = new ArrayList<String>();

  @SerializedName("frequency")
  private Double frequency = null;

  @SerializedName("id")
  private Long id = null;

  public CaseDistinctionConfigDto capitalizeFullVariants(Boolean capitalizeFullVariants) {
    this.capitalizeFullVariants = capitalizeFullVariants;
    return this;
  }

   /**
   * Get capitalizeFullVariants
   * @return capitalizeFullVariants
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCapitalizeFullVariants() {
    return capitalizeFullVariants;
  }

  public void setCapitalizeFullVariants(Boolean capitalizeFullVariants) {
    this.capitalizeFullVariants = capitalizeFullVariants;
  }

  public CaseDistinctionConfigDto customCapitalWords(List<String> customCapitalWords) {
    this.customCapitalWords = customCapitalWords;
    return this;
  }

  public CaseDistinctionConfigDto addCustomCapitalWordsItem(String customCapitalWordsItem) {
    this.customCapitalWords.add(customCapitalWordsItem);
    return this;
  }

   /**
   * Get customCapitalWords
   * @return customCapitalWords
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getCustomCapitalWords() {
    return customCapitalWords;
  }

  public void setCustomCapitalWords(List<String> customCapitalWords) {
    this.customCapitalWords = customCapitalWords;
  }

  public CaseDistinctionConfigDto frequency(Double frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getFrequency() {
    return frequency;
  }

  public void setFrequency(Double frequency) {
    this.frequency = frequency;
  }

  public CaseDistinctionConfigDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseDistinctionConfigDto caseDistinctionConfigDto = (CaseDistinctionConfigDto) o;
    return Objects.equals(this.capitalizeFullVariants, caseDistinctionConfigDto.capitalizeFullVariants) &&
        Objects.equals(this.customCapitalWords, caseDistinctionConfigDto.customCapitalWords) &&
        Objects.equals(this.frequency, caseDistinctionConfigDto.frequency) &&
        Objects.equals(this.id, caseDistinctionConfigDto.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capitalizeFullVariants, customCapitalWords, frequency, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseDistinctionConfigDto {\n");
    
    sb.append("    capitalizeFullVariants: ").append(toIndentedString(capitalizeFullVariants)).append("\n");
    sb.append("    customCapitalWords: ").append(toIndentedString(customCapitalWords)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

