/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * ExperimentMessage
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2024-09-11T10:24:25.694+06:00")
public class ExperimentMessage   {
  @SerializedName("content")
  private String content = null;

  @SerializedName("conversions")
  private Long conversions = null;

  @SerializedName("impressions")
  private Long impressions = null;

  @SerializedName("messageId")
  private Long messageId = null;

  @SerializedName("parentId")
  private Long parentId = null;

  @SerializedName("percentage")
  private BigDecimal percentage = null;

  @SerializedName("reach")
  private Long reach = null;

  @SerializedName("richContents")
  private List<RichContent> richContents = new ArrayList<RichContent>();

  @SerializedName("score")
  private Long score = null;

  @SerializedName("tags")
  private List<Tag> tags = new ArrayList<Tag>();

  public ExperimentMessage content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ExperimentMessage conversions(Long conversions) {
    this.conversions = conversions;
    return this;
  }

   /**
   * Get conversions
   * @return conversions
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getConversions() {
    return conversions;
  }

  public void setConversions(Long conversions) {
    this.conversions = conversions;
  }

  public ExperimentMessage impressions(Long impressions) {
    this.impressions = impressions;
    return this;
  }

   /**
   * Get impressions
   * @return impressions
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getImpressions() {
    return impressions;
  }

  public void setImpressions(Long impressions) {
    this.impressions = impressions;
  }

  public ExperimentMessage messageId(Long messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMessageId() {
    return messageId;
  }

  public void setMessageId(Long messageId) {
    this.messageId = messageId;
  }

  public ExperimentMessage parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  public ExperimentMessage percentage(BigDecimal percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * @return percentage
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getPercentage() {
    return percentage;
  }

  public void setPercentage(BigDecimal percentage) {
    this.percentage = percentage;
  }

  public ExperimentMessage reach(Long reach) {
    this.reach = reach;
    return this;
  }

   /**
   * Get reach
   * @return reach
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getReach() {
    return reach;
  }

  public void setReach(Long reach) {
    this.reach = reach;
  }

  public ExperimentMessage richContents(List<RichContent> richContents) {
    this.richContents = richContents;
    return this;
  }

  public ExperimentMessage addRichContentsItem(RichContent richContentsItem) {
    this.richContents.add(richContentsItem);
    return this;
  }

   /**
   * Get richContents
   * @return richContents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<RichContent> getRichContents() {
    return richContents;
  }

  public void setRichContents(List<RichContent> richContents) {
    this.richContents = richContents;
  }

  public ExperimentMessage score(Long score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getScore() {
    return score;
  }

  public void setScore(Long score) {
    this.score = score;
  }

  public ExperimentMessage tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public ExperimentMessage addTagsItem(Tag tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentMessage experimentMessage = (ExperimentMessage) o;
    return Objects.equals(this.content, experimentMessage.content) &&
        Objects.equals(this.conversions, experimentMessage.conversions) &&
        Objects.equals(this.impressions, experimentMessage.impressions) &&
        Objects.equals(this.messageId, experimentMessage.messageId) &&
        Objects.equals(this.parentId, experimentMessage.parentId) &&
        Objects.equals(this.percentage, experimentMessage.percentage) &&
        Objects.equals(this.reach, experimentMessage.reach) &&
        Objects.equals(this.richContents, experimentMessage.richContents) &&
        Objects.equals(this.score, experimentMessage.score) &&
        Objects.equals(this.tags, experimentMessage.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, conversions, impressions, messageId, parentId, percentage, reach, richContents, score, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentMessage {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    conversions: ").append(toIndentedString(conversions)).append("\n");
    sb.append("    impressions: ").append(toIndentedString(impressions)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    reach: ").append(toIndentedString(reach)).append("\n");
    sb.append("    richContents: ").append(toIndentedString(richContents)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

