/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExperimentMessage;
import io.swagger.client.model.GaIterationConfig;
import io.swagger.client.model.InitialIterationConfig;
import io.swagger.client.model.IterationCondition;
import io.swagger.client.model.IterationConfig;
import java.util.ArrayList;
import java.util.List;


/**
 * ExperimentClient
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2024-11-04T18:17:47.168+06:00")
public class ExperimentClient   {
  @SerializedName("channel")
  private String channel = null;

  @SerializedName("endDate_ui")
  private String endDateUi = null;

  @SerializedName("experimentName")
  private String experimentName = null;

  @SerializedName("gaIterationConfig")
  private GaIterationConfig gaIterationConfig = null;

  @SerializedName("initialIterationConfig")
  private InitialIterationConfig initialIterationConfig = null;

  @SerializedName("iterationCondition")
  private IterationCondition iterationCondition = null;

  @SerializedName("iterationConfiguration")
  private List<IterationConfig> iterationConfiguration = new ArrayList<IterationConfig>();

  @SerializedName("messages")
  private List<ExperimentMessage> messages = new ArrayList<ExperimentMessage>();

  @SerializedName("startDate_ui")
  private String startDateUi = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("DRAFT")
    DRAFT("DRAFT"),
    
    @SerializedName("READY")
    READY("READY"),
    
    @SerializedName("STARTED")
    STARTED("STARTED"),
    
    @SerializedName("CANCELLED")
    CANCELLED("CANCELLED"),
    
    @SerializedName("COMPLETED")
    COMPLETED("COMPLETED"),
    
    @SerializedName("DELETED")
    DELETED("DELETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  /**
   * Gets or Sets strategy
   */
  public enum StrategyEnum {
    @SerializedName("SINGLE_ITERATION_RANDOM_MSG")
    SINGLE_ITERATION_RANDOM_MSG("SINGLE_ITERATION_RANDOM_MSG"),
    
    @SerializedName("GENETIC_ALGORITHM_V0")
    GENETIC_ALGORITHM_V0("GENETIC_ALGORITHM_V0"),
    
    @SerializedName("BEST_MESSAGES_ROUNDS_GA")
    BEST_MESSAGES_ROUNDS_GA("BEST_MESSAGES_ROUNDS_GA");

    private String value;

    StrategyEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("strategy")
  private StrategyEnum strategy = null;

  @SerializedName("timezone_ui")
  private String timezoneUi = null;

  @SerializedName("userExpectedTargetGroupSize")
  private Long userExpectedTargetGroupSize = null;

  public ExperimentClient channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ExperimentClient endDateUi(String endDateUi) {
    this.endDateUi = endDateUi;
    return this;
  }

   /**
   * Get endDateUi
   * @return endDateUi
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndDateUi() {
    return endDateUi;
  }

  public void setEndDateUi(String endDateUi) {
    this.endDateUi = endDateUi;
  }

  public ExperimentClient experimentName(String experimentName) {
    this.experimentName = experimentName;
    return this;
  }

   /**
   * Get experimentName
   * @return experimentName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExperimentName() {
    return experimentName;
  }

  public void setExperimentName(String experimentName) {
    this.experimentName = experimentName;
  }

  public ExperimentClient gaIterationConfig(GaIterationConfig gaIterationConfig) {
    this.gaIterationConfig = gaIterationConfig;
    return this;
  }

   /**
   * Get gaIterationConfig
   * @return gaIterationConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public GaIterationConfig getGaIterationConfig() {
    return gaIterationConfig;
  }

  public void setGaIterationConfig(GaIterationConfig gaIterationConfig) {
    this.gaIterationConfig = gaIterationConfig;
  }

  public ExperimentClient initialIterationConfig(InitialIterationConfig initialIterationConfig) {
    this.initialIterationConfig = initialIterationConfig;
    return this;
  }

   /**
   * Get initialIterationConfig
   * @return initialIterationConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public InitialIterationConfig getInitialIterationConfig() {
    return initialIterationConfig;
  }

  public void setInitialIterationConfig(InitialIterationConfig initialIterationConfig) {
    this.initialIterationConfig = initialIterationConfig;
  }

  public ExperimentClient iterationCondition(IterationCondition iterationCondition) {
    this.iterationCondition = iterationCondition;
    return this;
  }

   /**
   * Get iterationCondition
   * @return iterationCondition
  **/
  @ApiModelProperty(example = "null", value = "")
  public IterationCondition getIterationCondition() {
    return iterationCondition;
  }

  public void setIterationCondition(IterationCondition iterationCondition) {
    this.iterationCondition = iterationCondition;
  }

  public ExperimentClient iterationConfiguration(List<IterationConfig> iterationConfiguration) {
    this.iterationConfiguration = iterationConfiguration;
    return this;
  }

  public ExperimentClient addIterationConfigurationItem(IterationConfig iterationConfigurationItem) {
    this.iterationConfiguration.add(iterationConfigurationItem);
    return this;
  }

   /**
   * Get iterationConfiguration
   * @return iterationConfiguration
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<IterationConfig> getIterationConfiguration() {
    return iterationConfiguration;
  }

  public void setIterationConfiguration(List<IterationConfig> iterationConfiguration) {
    this.iterationConfiguration = iterationConfiguration;
  }

  public ExperimentClient messages(List<ExperimentMessage> messages) {
    this.messages = messages;
    return this;
  }

  public ExperimentClient addMessagesItem(ExperimentMessage messagesItem) {
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ExperimentMessage> getMessages() {
    return messages;
  }

  public void setMessages(List<ExperimentMessage> messages) {
    this.messages = messages;
  }

  public ExperimentClient startDateUi(String startDateUi) {
    this.startDateUi = startDateUi;
    return this;
  }

   /**
   * Get startDateUi
   * @return startDateUi
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDateUi() {
    return startDateUi;
  }

  public void setStartDateUi(String startDateUi) {
    this.startDateUi = startDateUi;
  }

  public ExperimentClient status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ExperimentClient strategy(StrategyEnum strategy) {
    this.strategy = strategy;
    return this;
  }

   /**
   * Get strategy
   * @return strategy
  **/
  @ApiModelProperty(example = "null", value = "")
  public StrategyEnum getStrategy() {
    return strategy;
  }

  public void setStrategy(StrategyEnum strategy) {
    this.strategy = strategy;
  }

  public ExperimentClient timezoneUi(String timezoneUi) {
    this.timezoneUi = timezoneUi;
    return this;
  }

   /**
   * Get timezoneUi
   * @return timezoneUi
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimezoneUi() {
    return timezoneUi;
  }

  public void setTimezoneUi(String timezoneUi) {
    this.timezoneUi = timezoneUi;
  }

  public ExperimentClient userExpectedTargetGroupSize(Long userExpectedTargetGroupSize) {
    this.userExpectedTargetGroupSize = userExpectedTargetGroupSize;
    return this;
  }

   /**
   * Get userExpectedTargetGroupSize
   * @return userExpectedTargetGroupSize
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUserExpectedTargetGroupSize() {
    return userExpectedTargetGroupSize;
  }

  public void setUserExpectedTargetGroupSize(Long userExpectedTargetGroupSize) {
    this.userExpectedTargetGroupSize = userExpectedTargetGroupSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentClient experimentClient = (ExperimentClient) o;
    return Objects.equals(this.channel, experimentClient.channel) &&
        Objects.equals(this.endDateUi, experimentClient.endDateUi) &&
        Objects.equals(this.experimentName, experimentClient.experimentName) &&
        Objects.equals(this.gaIterationConfig, experimentClient.gaIterationConfig) &&
        Objects.equals(this.initialIterationConfig, experimentClient.initialIterationConfig) &&
        Objects.equals(this.iterationCondition, experimentClient.iterationCondition) &&
        Objects.equals(this.iterationConfiguration, experimentClient.iterationConfiguration) &&
        Objects.equals(this.messages, experimentClient.messages) &&
        Objects.equals(this.startDateUi, experimentClient.startDateUi) &&
        Objects.equals(this.status, experimentClient.status) &&
        Objects.equals(this.strategy, experimentClient.strategy) &&
        Objects.equals(this.timezoneUi, experimentClient.timezoneUi) &&
        Objects.equals(this.userExpectedTargetGroupSize, experimentClient.userExpectedTargetGroupSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, endDateUi, experimentName, gaIterationConfig, initialIterationConfig, iterationCondition, iterationConfiguration, messages, startDateUi, status, strategy, timezoneUi, userExpectedTargetGroupSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentClient {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    endDateUi: ").append(toIndentedString(endDateUi)).append("\n");
    sb.append("    experimentName: ").append(toIndentedString(experimentName)).append("\n");
    sb.append("    gaIterationConfig: ").append(toIndentedString(gaIterationConfig)).append("\n");
    sb.append("    initialIterationConfig: ").append(toIndentedString(initialIterationConfig)).append("\n");
    sb.append("    iterationCondition: ").append(toIndentedString(iterationCondition)).append("\n");
    sb.append("    iterationConfiguration: ").append(toIndentedString(iterationConfiguration)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    startDateUi: ").append(toIndentedString(startDateUi)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("    timezoneUi: ").append(toIndentedString(timezoneUi)).append("\n");
    sb.append("    userExpectedTargetGroupSize: ").append(toIndentedString(userExpectedTargetGroupSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

