/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MessageReportDto;
import io.swagger.client.model.ReportIterationDto;
import java.util.ArrayList;
import java.util.List;


/**
 * ExperimentIterationReport
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class ExperimentIterationReport   {
  @SerializedName("experimentId")
  private Long experimentId = null;

  @SerializedName("experimentName")
  private String experimentName = null;

  @SerializedName("iterations")
  private List<ReportIterationDto> iterations = new ArrayList<ReportIterationDto>();

  @SerializedName("parentMessage")
  private MessageReportDto parentMessage = null;

  public ExperimentIterationReport experimentId(Long experimentId) {
    this.experimentId = experimentId;
    return this;
  }

   /**
   * Get experimentId
   * @return experimentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getExperimentId() {
    return experimentId;
  }

  public void setExperimentId(Long experimentId) {
    this.experimentId = experimentId;
  }

  public ExperimentIterationReport experimentName(String experimentName) {
    this.experimentName = experimentName;
    return this;
  }

   /**
   * Get experimentName
   * @return experimentName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExperimentName() {
    return experimentName;
  }

  public void setExperimentName(String experimentName) {
    this.experimentName = experimentName;
  }

  public ExperimentIterationReport iterations(List<ReportIterationDto> iterations) {
    this.iterations = iterations;
    return this;
  }

  public ExperimentIterationReport addIterationsItem(ReportIterationDto iterationsItem) {
    this.iterations.add(iterationsItem);
    return this;
  }

   /**
   * Get iterations
   * @return iterations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ReportIterationDto> getIterations() {
    return iterations;
  }

  public void setIterations(List<ReportIterationDto> iterations) {
    this.iterations = iterations;
  }

  public ExperimentIterationReport parentMessage(MessageReportDto parentMessage) {
    this.parentMessage = parentMessage;
    return this;
  }

   /**
   * Get parentMessage
   * @return parentMessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public MessageReportDto getParentMessage() {
    return parentMessage;
  }

  public void setParentMessage(MessageReportDto parentMessage) {
    this.parentMessage = parentMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentIterationReport experimentIterationReport = (ExperimentIterationReport) o;
    return Objects.equals(this.experimentId, experimentIterationReport.experimentId) &&
        Objects.equals(this.experimentName, experimentIterationReport.experimentName) &&
        Objects.equals(this.iterations, experimentIterationReport.iterations) &&
        Objects.equals(this.parentMessage, experimentIterationReport.parentMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(experimentId, experimentName, iterations, parentMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentIterationReport {\n");
    
    sb.append("    experimentId: ").append(toIndentedString(experimentId)).append("\n");
    sb.append("    experimentName: ").append(toIndentedString(experimentName)).append("\n");
    sb.append("    iterations: ").append(toIndentedString(iterations)).append("\n");
    sb.append("    parentMessage: ").append(toIndentedString(parentMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

