/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GlobalMessageRecordChildTag;
import java.util.ArrayList;
import java.util.List;


/**
 * GlobalMessageRecordTag
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-30T15:47:59.165+06:00")
public class GlobalMessageRecordTag   {
  @SerializedName("segment")
  private String segment = null;

  @SerializedName("topMessages")
  private List<GlobalMessageRecordChildTag> topMessages = new ArrayList<GlobalMessageRecordChildTag>();

  @SerializedName("totalUsage")
  private Long totalUsage = null;

  public GlobalMessageRecordTag segment(String segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSegment() {
    return segment;
  }

  public void setSegment(String segment) {
    this.segment = segment;
  }

  public GlobalMessageRecordTag topMessages(List<GlobalMessageRecordChildTag> topMessages) {
    this.topMessages = topMessages;
    return this;
  }

  public GlobalMessageRecordTag addTopMessagesItem(GlobalMessageRecordChildTag topMessagesItem) {
    this.topMessages.add(topMessagesItem);
    return this;
  }

   /**
   * Get topMessages
   * @return topMessages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<GlobalMessageRecordChildTag> getTopMessages() {
    return topMessages;
  }

  public void setTopMessages(List<GlobalMessageRecordChildTag> topMessages) {
    this.topMessages = topMessages;
  }

  public GlobalMessageRecordTag totalUsage(Long totalUsage) {
    this.totalUsage = totalUsage;
    return this;
  }

   /**
   * Get totalUsage
   * @return totalUsage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalUsage() {
    return totalUsage;
  }

  public void setTotalUsage(Long totalUsage) {
    this.totalUsage = totalUsage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlobalMessageRecordTag globalMessageRecordTag = (GlobalMessageRecordTag) o;
    return Objects.equals(this.segment, globalMessageRecordTag.segment) &&
        Objects.equals(this.topMessages, globalMessageRecordTag.topMessages) &&
        Objects.equals(this.totalUsage, globalMessageRecordTag.totalUsage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(segment, topMessages, totalUsage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlobalMessageRecordTag {\n");
    
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    topMessages: ").append(toIndentedString(topMessages)).append("\n");
    sb.append("    totalUsage: ").append(toIndentedString(totalUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

