/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DayOfWeekStats;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * ReportingRecordDayOfWeekStats
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class ReportingRecordDayOfWeekStats   {
  @SerializedName("channel")
  private Map<String, Map<String, DayOfWeekStats>> channel = new HashMap<String, Map<String, DayOfWeekStats>>();

  @SerializedName("total")
  private Map<String, DayOfWeekStats> total = new HashMap<String, DayOfWeekStats>();

  public ReportingRecordDayOfWeekStats channel(Map<String, Map<String, DayOfWeekStats>> channel) {
    this.channel = channel;
    return this;
  }

  public ReportingRecordDayOfWeekStats putChannelItem(String key, Map<String, DayOfWeekStats> channelItem) {
    this.channel.put(key, channelItem);
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Map<String, DayOfWeekStats>> getChannel() {
    return channel;
  }

  public void setChannel(Map<String, Map<String, DayOfWeekStats>> channel) {
    this.channel = channel;
  }

  public ReportingRecordDayOfWeekStats total(Map<String, DayOfWeekStats> total) {
    this.total = total;
    return this;
  }

  public ReportingRecordDayOfWeekStats putTotalItem(String key, DayOfWeekStats totalItem) {
    this.total.put(key, totalItem);
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, DayOfWeekStats> getTotal() {
    return total;
  }

  public void setTotal(Map<String, DayOfWeekStats> total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportingRecordDayOfWeekStats reportingRecordDayOfWeekStats = (ReportingRecordDayOfWeekStats) o;
    return Objects.equals(this.channel, reportingRecordDayOfWeekStats.channel) &&
        Objects.equals(this.total, reportingRecordDayOfWeekStats.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportingRecordDayOfWeekStats {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

