/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * RichContent
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2024-09-16T11:21:22.833+06:00")
public class RichContent   {
  @SerializedName("position")
  private Integer position = null;

  @SerializedName("positionId")
  private Long positionId = null;

  @SerializedName("richContentID")
  private Long richContentID = null;

  @SerializedName("tags")
  private List<Tag> tags = new ArrayList<Tag>();

  @SerializedName("text")
  private String text = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("TEXT")
    TEXT("TEXT"),
    
    @SerializedName("IMAGE")
    IMAGE("IMAGE"),
    
    @SerializedName("VIDEO")
    VIDEO("VIDEO"),
    
    @SerializedName("AUDIO")
    AUDIO("AUDIO"),
    
    @SerializedName("DOCUMENT")
    DOCUMENT("DOCUMENT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public RichContent position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public RichContent positionId(Long positionId) {
    this.positionId = positionId;
    return this;
  }

   /**
   * Get positionId
   * @return positionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPositionId() {
    return positionId;
  }

  public void setPositionId(Long positionId) {
    this.positionId = positionId;
  }

  public RichContent richContentID(Long richContentID) {
    this.richContentID = richContentID;
    return this;
  }

   /**
   * Get richContentID
   * @return richContentID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getRichContentID() {
    return richContentID;
  }

  public void setRichContentID(Long richContentID) {
    this.richContentID = richContentID;
  }

  public RichContent tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public RichContent addTagsItem(Tag tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }

  public RichContent text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public RichContent type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RichContent richContent = (RichContent) o;
    return Objects.equals(this.position, richContent.position) &&
        Objects.equals(this.positionId, richContent.positionId) &&
        Objects.equals(this.richContentID, richContent.richContentID) &&
        Objects.equals(this.tags, richContent.tags) &&
        Objects.equals(this.text, richContent.text) &&
        Objects.equals(this.type, richContent.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(position, positionId, richContentID, tags, text, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RichContent {\n");
    
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    positionId: ").append(toIndentedString(positionId)).append("\n");
    sb.append("    richContentID: ").append(toIndentedString(richContentID)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

