/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CaseDistinctionConfigDto;
import io.swagger.client.model.EmoticonConfigDto;
import io.swagger.client.model.FilteredOutConfigDto;
import io.swagger.client.model.HyphenStylesConfigDto;
import io.swagger.client.model.PunctuationMarkConfigDto;
import io.swagger.client.model.StyleFormatConfigDto;


/**
 * StylesConfigDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class StylesConfigDto   {
  @SerializedName("caseDistinctionConfig")
  private CaseDistinctionConfigDto caseDistinctionConfig = null;

  @SerializedName("emoticonConfig")
  private EmoticonConfigDto emoticonConfig = null;

  @SerializedName("filteredOutConfig")
  private FilteredOutConfigDto filteredOutConfig = null;

  @SerializedName("hyphenStylesConfig")
  private HyphenStylesConfigDto hyphenStylesConfig = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("punctuationMarkConfig")
  private PunctuationMarkConfigDto punctuationMarkConfig = null;

  @SerializedName("styleFormatConfig")
  private StyleFormatConfigDto styleFormatConfig = null;

  public StylesConfigDto caseDistinctionConfig(CaseDistinctionConfigDto caseDistinctionConfig) {
    this.caseDistinctionConfig = caseDistinctionConfig;
    return this;
  }

   /**
   * Get caseDistinctionConfig
   * @return caseDistinctionConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public CaseDistinctionConfigDto getCaseDistinctionConfig() {
    return caseDistinctionConfig;
  }

  public void setCaseDistinctionConfig(CaseDistinctionConfigDto caseDistinctionConfig) {
    this.caseDistinctionConfig = caseDistinctionConfig;
  }

  public StylesConfigDto emoticonConfig(EmoticonConfigDto emoticonConfig) {
    this.emoticonConfig = emoticonConfig;
    return this;
  }

   /**
   * Get emoticonConfig
   * @return emoticonConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public EmoticonConfigDto getEmoticonConfig() {
    return emoticonConfig;
  }

  public void setEmoticonConfig(EmoticonConfigDto emoticonConfig) {
    this.emoticonConfig = emoticonConfig;
  }

  public StylesConfigDto filteredOutConfig(FilteredOutConfigDto filteredOutConfig) {
    this.filteredOutConfig = filteredOutConfig;
    return this;
  }

   /**
   * Get filteredOutConfig
   * @return filteredOutConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public FilteredOutConfigDto getFilteredOutConfig() {
    return filteredOutConfig;
  }

  public void setFilteredOutConfig(FilteredOutConfigDto filteredOutConfig) {
    this.filteredOutConfig = filteredOutConfig;
  }

  public StylesConfigDto hyphenStylesConfig(HyphenStylesConfigDto hyphenStylesConfig) {
    this.hyphenStylesConfig = hyphenStylesConfig;
    return this;
  }

   /**
   * Get hyphenStylesConfig
   * @return hyphenStylesConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public HyphenStylesConfigDto getHyphenStylesConfig() {
    return hyphenStylesConfig;
  }

  public void setHyphenStylesConfig(HyphenStylesConfigDto hyphenStylesConfig) {
    this.hyphenStylesConfig = hyphenStylesConfig;
  }

  public StylesConfigDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public StylesConfigDto punctuationMarkConfig(PunctuationMarkConfigDto punctuationMarkConfig) {
    this.punctuationMarkConfig = punctuationMarkConfig;
    return this;
  }

   /**
   * Get punctuationMarkConfig
   * @return punctuationMarkConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public PunctuationMarkConfigDto getPunctuationMarkConfig() {
    return punctuationMarkConfig;
  }

  public void setPunctuationMarkConfig(PunctuationMarkConfigDto punctuationMarkConfig) {
    this.punctuationMarkConfig = punctuationMarkConfig;
  }

  public StylesConfigDto styleFormatConfig(StyleFormatConfigDto styleFormatConfig) {
    this.styleFormatConfig = styleFormatConfig;
    return this;
  }

   /**
   * Get styleFormatConfig
   * @return styleFormatConfig
  **/
  @ApiModelProperty(example = "null", value = "")
  public StyleFormatConfigDto getStyleFormatConfig() {
    return styleFormatConfig;
  }

  public void setStyleFormatConfig(StyleFormatConfigDto styleFormatConfig) {
    this.styleFormatConfig = styleFormatConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StylesConfigDto stylesConfigDto = (StylesConfigDto) o;
    return Objects.equals(this.caseDistinctionConfig, stylesConfigDto.caseDistinctionConfig) &&
        Objects.equals(this.emoticonConfig, stylesConfigDto.emoticonConfig) &&
        Objects.equals(this.filteredOutConfig, stylesConfigDto.filteredOutConfig) &&
        Objects.equals(this.hyphenStylesConfig, stylesConfigDto.hyphenStylesConfig) &&
        Objects.equals(this.id, stylesConfigDto.id) &&
        Objects.equals(this.punctuationMarkConfig, stylesConfigDto.punctuationMarkConfig) &&
        Objects.equals(this.styleFormatConfig, stylesConfigDto.styleFormatConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseDistinctionConfig, emoticonConfig, filteredOutConfig, hyphenStylesConfig, id, punctuationMarkConfig, styleFormatConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StylesConfigDto {\n");
    
    sb.append("    caseDistinctionConfig: ").append(toIndentedString(caseDistinctionConfig)).append("\n");
    sb.append("    emoticonConfig: ").append(toIndentedString(emoticonConfig)).append("\n");
    sb.append("    filteredOutConfig: ").append(toIndentedString(filteredOutConfig)).append("\n");
    sb.append("    hyphenStylesConfig: ").append(toIndentedString(hyphenStylesConfig)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    punctuationMarkConfig: ").append(toIndentedString(punctuationMarkConfig)).append("\n");
    sb.append("    styleFormatConfig: ").append(toIndentedString(styleFormatConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

