/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExperimentMessage;
import java.util.ArrayList;
import java.util.List;


/**
 * TargetGroupMessage
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T19:02:02.404+06:00")
public class TargetGroupMessage   {
  @SerializedName("messages")
  private List<ExperimentMessage> messages = new ArrayList<ExperimentMessage>();

  @SerializedName("targetGroupId")
  private Long targetGroupId = null;

  @SerializedName("targetGroupName")
  private String targetGroupName = null;

  public TargetGroupMessage messages(List<ExperimentMessage> messages) {
    this.messages = messages;
    return this;
  }

  public TargetGroupMessage addMessagesItem(ExperimentMessage messagesItem) {
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ExperimentMessage> getMessages() {
    return messages;
  }

  public void setMessages(List<ExperimentMessage> messages) {
    this.messages = messages;
  }

  public TargetGroupMessage targetGroupId(Long targetGroupId) {
    this.targetGroupId = targetGroupId;
    return this;
  }

   /**
   * Get targetGroupId
   * @return targetGroupId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTargetGroupId() {
    return targetGroupId;
  }

  public void setTargetGroupId(Long targetGroupId) {
    this.targetGroupId = targetGroupId;
  }

  public TargetGroupMessage targetGroupName(String targetGroupName) {
    this.targetGroupName = targetGroupName;
    return this;
  }

   /**
   * Get targetGroupName
   * @return targetGroupName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTargetGroupName() {
    return targetGroupName;
  }

  public void setTargetGroupName(String targetGroupName) {
    this.targetGroupName = targetGroupName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetGroupMessage targetGroupMessage = (TargetGroupMessage) o;
    return Objects.equals(this.messages, targetGroupMessage.messages) &&
        Objects.equals(this.targetGroupId, targetGroupMessage.targetGroupId) &&
        Objects.equals(this.targetGroupName, targetGroupMessage.targetGroupName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, targetGroupId, targetGroupName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetGroupMessage {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    targetGroupId: ").append(toIndentedString(targetGroupId)).append("\n");
    sb.append("    targetGroupName: ").append(toIndentedString(targetGroupName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

