/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * TemplateContextConfig
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-29T18:38:19.753+06:00")
public class TemplateContextConfig   {
  @SerializedName("default")
  private Boolean _default = null;

  @SerializedName("htmlTemplate")
  private String htmlTemplate = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("messageId")
  private Long messageId = null;

  @SerializedName("placeholders")
  private List<String> placeholders = new ArrayList<String>();

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("targetUrl")
  private String targetUrl = null;

  @SerializedName("unsubscribeLink")
  private String unsubscribeLink = null;

  public TemplateContextConfig _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }

  public TemplateContextConfig htmlTemplate(String htmlTemplate) {
    this.htmlTemplate = htmlTemplate;
    return this;
  }

   /**
   * Get htmlTemplate
   * @return htmlTemplate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHtmlTemplate() {
    return htmlTemplate;
  }

  public void setHtmlTemplate(String htmlTemplate) {
    this.htmlTemplate = htmlTemplate;
  }

  public TemplateContextConfig id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TemplateContextConfig messageId(Long messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMessageId() {
    return messageId;
  }

  public void setMessageId(Long messageId) {
    this.messageId = messageId;
  }

  public TemplateContextConfig placeholders(List<String> placeholders) {
    this.placeholders = placeholders;
    return this;
  }

  public TemplateContextConfig addPlaceholdersItem(String placeholdersItem) {
    this.placeholders.add(placeholdersItem);
    return this;
  }

   /**
   * Get placeholders
   * @return placeholders
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getPlaceholders() {
    return placeholders;
  }

  public void setPlaceholders(List<String> placeholders) {
    this.placeholders = placeholders;
  }

  public TemplateContextConfig subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public TemplateContextConfig targetUrl(String targetUrl) {
    this.targetUrl = targetUrl;
    return this;
  }

   /**
   * Get targetUrl
   * @return targetUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTargetUrl() {
    return targetUrl;
  }

  public void setTargetUrl(String targetUrl) {
    this.targetUrl = targetUrl;
  }

  public TemplateContextConfig unsubscribeLink(String unsubscribeLink) {
    this.unsubscribeLink = unsubscribeLink;
    return this;
  }

   /**
   * Get unsubscribeLink
   * @return unsubscribeLink
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUnsubscribeLink() {
    return unsubscribeLink;
  }

  public void setUnsubscribeLink(String unsubscribeLink) {
    this.unsubscribeLink = unsubscribeLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateContextConfig templateContextConfig = (TemplateContextConfig) o;
    return Objects.equals(this._default, templateContextConfig._default) &&
        Objects.equals(this.htmlTemplate, templateContextConfig.htmlTemplate) &&
        Objects.equals(this.id, templateContextConfig.id) &&
        Objects.equals(this.messageId, templateContextConfig.messageId) &&
        Objects.equals(this.placeholders, templateContextConfig.placeholders) &&
        Objects.equals(this.subject, templateContextConfig.subject) &&
        Objects.equals(this.targetUrl, templateContextConfig.targetUrl) &&
        Objects.equals(this.unsubscribeLink, templateContextConfig.unsubscribeLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, htmlTemplate, id, messageId, placeholders, subject, targetUrl, unsubscribeLink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateContextConfig {\n");
    
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    htmlTemplate: ").append(toIndentedString(htmlTemplate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    placeholders: ").append(toIndentedString(placeholders)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("    unsubscribeLink: ").append(toIndentedString(unsubscribeLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

