/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Message;
import io.swagger.client.model.MessageRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessageclientcontrollerApi
 */
public class MessageclientcontrollerApiTest {

    private final MessageclientcontrollerApi api = new MessageclientcontrollerApi();

    
    /**
     * getMessages
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessagesUsingGETTest() throws ApiException {
        List<Long> id = null;
        List<String> status = null;
        // List<Message> response = api.getMessagesUsingGET(id, status);

        // TODO: test validations
    }
    
    /**
     * getMessages
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessagesUsingPOSTTest() throws ApiException {
        MessageRequest request = null;
        // List<Message> response = api.getMessagesUsingPOST(request);

        // TODO: test validations
    }
    
}
